In [30]:
import pandas as pd
import numpy as np
import tensorflow as tf

# filepath_dict = {'A_Tree_Grows_In_Brooklyn.txt':   ('BoW/A_Tree_Grows_In_Brooklyn_BoW.txt', 1),
#                  'Atlas_Shrugged.txt': ('BoW/Atlas_Shrugged_BoW.txt', 3),
#                  'Huckleberry_Finn.txt':   ('BoW/Huckleberry_Finn_BoW.txt', 2),
#                  'The_Awakening.txt': ('BoW/The_Awakening_BoW.txt', 4)}


# text_BoW_files = ['BoW/A_Tree_Grows_In_Brooklyn_BoW.txt', 'BoW/Atlas_Shrugged_BoW.txt', 
#               'BoW/Huckleberry_Finn_BoW.txt', 'BoW/The_Awakening_BoW.txt']

# # text_files = ['data/A_Tree_Grows_In_Brooklyn.txt', 'data/Atlas_Shrugged.txt', 
# #               'data/Huckleberry_Finn.txt', 'data/The_Awakening.txt']
# text_files = ['data/test1.txt', 'data/test2.txt', 'data/test3.txt', 'data/test4.txt']

rank = [4.33, 4.17, 4.01, 3.99, 4.04, 3.84, 4.03, 3.54, 4.13, 3.62, 3.68, 3.92, 3.75, 3.66, 3.83]

In [31]:
# opening the file in read mode
my_file = open("data_list.txt", "r")

# reading the file
path_data = my_file.read()

# replacing end splitting the text
# when newline ('\n') is seen.
paths = path_data.split("\n")
print(paths)
my_file.close()

['FullTexts/A_Tree_Grows_In_Brooklyn.txt', 'FullTexts/Atlas_Shrugged.txt', 'FullTexts/Collected_Poems_Emily_Dickinson.txt', 'FullTexts/Farenheit_451.txt', 'FullTexts/Grapes_of_Wrath.txt', 'FullTexts/Huckleberry_Finn.txt', 'FullTexts/Incidents_in_The_Life_of_a_Slave_Girl.txt', 'FullTexts/Maggie_A_Girl_of_The_Streets.txt', 'FullTexts/Slaughterhouse-five.txt', 'FullTexts/The_Awakening.txt', 'FullTexts/The_Cruicble.txt', 'FullTexts/The_House_of_Mirth.txt', 'FullTexts/The_Jungle.txt', 'FullTexts/The_Portrait_of_a_Lady.txt', 'FullTexts/Walden.txt']


In [32]:
contents = []
# paths = ['data/A_Tree_Grows_In_Brooklyn.txt', 'data/Atlas_Shrugged.txt', 'data/Huckleberry_Finn.txt', 'data/The_Awakening.txt']
# paths = ['data/test1.txt', 'data/test2.txt', 'data/test3.txt', 'data/test4.txt']

for path in paths:
    with open(path, 'r', encoding='utf-8') as f:     # encoding='utf-8'不行
        for line in f.readlines():
            contents.append(line)
    f.close()
    
data = pd.DataFrame([])
data["text"] = contents
data["label"] = rank
data

text  label
0   A Tree Grows in Brooklyn Betty Smith A Tree G...   4.33
1   CONTENTS PART I NON- CONTRAD ICT ION I THE TH...   4.17
2   This is my letter to the world,    That never...   4.01
3   oneThe Hearth and the SalamanderIt was a plea...   3.99
4   THE MODERN LIBRARY OF THE WORLD’S BEST BOOKS ...   4.04
5   The Project Gutenberg eBook of The Adventures...   3.84
6   I. ChildhoodI was born a slave; but I never k...   4.03
7   Chapter IA very little boy stood upon a heap ...   3.54
8   OneAll this happened, more or less. The war p...   4.13
9   THE AWAKENINGIA green and yellow parrot, whic...   3.62
10  The Crucible Arthur MillerA NOTE ON THE HISTO...   3.68
11  Selden paused in surprise. In the afternoon r...   3.92
12  CHAPTER IIt was four o’clock when the ceremon...   3.75
13  THE PORTRAIT OF A LADYCHAPTER IUnder certain ...   3.66
14  WALDENEconomyWhen I wrote the following pages...   3.83

In [33]:
data.label.unique()

array([4.33, 4.17, 4.01, 3.99, 4.04, 3.84, 4.03, 3.54, 4.13, 3.62, 3.68,
       3.92, 3.75, 3.66, 3.83])

In [34]:
import re
token = re.compile('[A-Za-z]+|[!?,.()]')

In [35]:
def reg_text(text):
    new_text = token.findall(text)
    new_text = [word.lower() for word in new_text]
    return new_text

In [36]:
data['text'] = data.text.apply(reg_text)

In [37]:
word_set = set()
for text in data.text:
    for word in text:
        word_set.add(word) 
max_word = len(word_set) + 1
max_word

45137

In [38]:
word_list = list(word_set)
word_list.index('school')

1817

In [39]:
word_index =  dict((word, word_list.index(word) + 1) for word in word_list)
word_index

{'invade': 1,
 'reasonable': 2,
 'peremptory': 3,
 'pondssometimes': 4,
 'oleariam': 5,
 'bejuggled': 6,
 'dislike': 7,
 'veterans': 8,
 'reposed': 9,
 'plead': 10,
 'panion': 11,
 'tation': 12,
 'haines': 13,
 'starkest': 14,
 'recuperate': 15,
 'cute': 16,
 'slowed': 17,
 'seeds': 18,
 'asrich': 19,
 'problemin': 20,
 'fortaking': 21,
 'camein': 22,
 'dragon': 23,
 'procaine': 24,
 'vats': 25,
 'jelly': 26,
 'awalk': 27,
 'renownthat': 28,
 'atmontag': 29,
 'solemnly': 30,
 'swiftcurrent': 31,
 'discoverable': 32,
 'incurring': 33,
 'demonstrated': 34,
 'shove': 35,
 'levipes': 36,
 'pictorial': 37,
 'denser': 38,
 'imperturbability': 39,
 'foremost': 40,
 'hindering': 41,
 'ortoo': 42,
 'yair': 43,
 'rosashara': 44,
 'thatfirst': 45,
 'unfocusing': 46,
 'tenants': 47,
 'accepts': 48,
 'grossly': 49,
 'suspect': 50,
 'greedily': 51,
 'topsfield': 52,
 'whitened': 53,
 'bestfriends': 54,
 'hurry': 55,
 'poised': 56,
 'catch': 57,
 'levy': 58,
 'volition': 59,
 'sublimity': 60,
 'jitte

In [40]:
data_ok = data.text.apply(lambda x: [word_index.get(word, 0) for word in x])
len(data_ok.iloc[2])

37434

In [41]:
maxlen = max(len(x) for x in data_ok)
maxlen

667033

In [42]:
data_ok = tf.keras.preprocessing.sequence.pad_sequences(data_ok.values, maxlen=maxlen)

In [43]:
data_ok.shape

(15, 667033)

In [44]:
data.label.values

array([4.33, 4.17, 4.01, 3.99, 4.04, 3.84, 4.03, 3.54, 4.13, 3.62, 3.68,
       3.92, 3.75, 3.66, 3.83])

In [45]:
from tensorflow import keras
from tensorflow.keras import layers

In [17]:
def train_model():
    model = keras.Sequential()
    model.add(layers.Embedding(max_word, 16, input_length=maxlen))
    model.add(layers.Bidirectional(layers.LSTM(64,
                         dropout=0.2,
                         recurrent_dropout=0.5)))
    model.add(layers.Dropout(0.5))
    model.add(layers.Dense(1, activation='sigmoid'))
    model.compile(optimizer=keras.optimizers.RMSprop(),
              loss='binary_crossentropy',
              metrics=['acc'])
    return model

In [18]:
model = train_model()

In [19]:
learning_rate_reduction = keras.callbacks.ReduceLROnPlateau(monitor='val_loss', patience=3, factor=0.3, min_lr=0.00001)

In [20]:
history = model.fit(data_ok, 
                     data.label.values, 
                     epochs=30, 
                     batch_size=128, 
                     validation_split=0.2,
                     callbacks=[learning_rate_reduction])

Epoch 1/30
1/1 [==============================] - 0s 216ms/step - loss: 0.7035 - acc: 0.3333 - val_loss: 0.5172 - val_acc: 0.0000e+00
Epoch 2/30
1/1 [==============================] - 0s 9ms/step - loss: 0.6239 - acc: 0.3333 - val_loss: 0.3661 - val_acc: 0.0000e+00
Epoch 3/30
1/1 [==============================] - 0s 9ms/step - loss: 0.5775 - acc: 0.3333 - val_loss: 0.2221 - val_acc: 0.0000e+00
Epoch 4/30
1/1 [==============================] - 0s 8ms/step - loss: 0.5099 - acc: 0.3333 - val_loss: 0.0458 - val_acc: 0.0000e+00
Epoch 5/30
1/1 [==============================] - 0s 9ms/step - loss: 0.4396 - acc: 0.3333 - val_loss: -0.1791 - val_acc: 0.0000e+00
Epoch 6/30
1/1 [==============================] - 0s 8ms/step - loss: 0.3499 - acc: 0.3333 - val_loss: -0.4743 - val_acc: 0.0000e+00
Epoch 7/30
1/1 [==============================] - 0s 9ms/step - loss: 0.2064 - acc: 0.3333 - val_loss: -0.8681 - val_acc: 0.0000e+00
Epoch 8/30
1/1 [==============================] - 0s 8ms/step - loss: 0

In [21]:
model.save('model/model1.keras')

In [22]:
model = keras.models.load_model('model/model1.keras')
model.predict(data_ok)

array([[0.99999946],
       [0.9999995 ],
       [0.9999995 ],
       [0.9999994 ]], dtype=float32)